# Energy Cost Management
# Added by Claude.ai on 31 July 2025
homeassistant: 
input_number:
  electricity_rate:
    name: "Electricity Rate (per kWh)"
    min: 0
    max: 10
    step: 0.01
    initial: 1.65  # Set your actual rate
    unit_of_measurement: "R/kWh"
    icon: mdi:currency-usd
#------------------------------------------------------------------------------------------------------------------------------------------------  
# Added by Claude.ai on 31 July 2025
  daily_connection_fee:
    name: "Daily Connection Fee"
    min: 0
    max: 50
    step: 0.01
    initial: 12.50  # Set your actual daily fee
    unit_of_measurement: "R/day"
    icon: mdi:transmission-tower
#------------------------------------------------------------------------------------------------------------------------------------------------  
# Added by Claude.ai on 31 July 2025
input_select:
  electricity_tariff_type:
    name: "Tariff Type"
    options:
      - "Standard"
      - "Time of Use"
      - "Peak/Off-Peak"
    initial: "Standard"
    icon: mdi:clock-time-four
#------------------------------------------------------------------------------------------------------------------------------------------------  
