binary_sensor:
  - platform: hikvision
    host: 192.168.1.144
    username: !secret hikvision_user
    password: !secret hikvision_password
    name: DVR Inside
  - platform: hikvision
    host: 192.168.1.151
    username: !secret hikvision_user
    password: !secret hikvision_password
    name: Dvr Outside
    