zone_bypass_code:
  name: Bypass Zone
  description: Bypass zone if code not saved in options.
  target:
    entity:
      integration: ids_hyyp
      domain: switch
  fields:
    bypass_code:
      name: Zone bypass code
      description: Partition or Site level bypass code.
      required: true
      example: 1234
      default: 1234
      selector:
        text:
trigger_automation:
  name: Trigger Automation
  description: Trigger automation if arm code not saved.
  target:
    entity:
      integration: ids_hyyp
      domain: button
  fields:
    arm_code:
      name: Arm code
      description: Site level arm code.
      required: true
      example: 1234
      default: 1234
      selector:
        text:
